### ISSUE TITLE
Laravel requires a higher level of Ramsey/UUID

### ISSUE THREAD

**Issue by stephenburgess8** [wingify/vwo-php-sdk#11]
Hello,

I'm attempting to install this SDK in a new project after having implemented it in another project. The new project is a Laravel project using [v9.2.0](https://laravel-news.com/laravel-9-2-0). This version of Laravel [requires](https://github.com/laravel/framework/blob/9.x/composer.json#L33) `ramsey/uuid` with a version of `^4.2.2`.

In the initial commit for `vwo-php-sdk`, `ramsey/uuid` is [required](https://github.com/wingify/vwo-php-sdk/blob/master/composer.json#L12) with a version of  `^3.8`. Because of this lower version of the library, I'm unable to install the `vwo-php-sdk` in my project.

Here's the output from when I try to require the package:

`composer require vwo/vwo-php-sdk`

`Your requirements could not be resolved to an installable set of packages.`
```
Problem 1
    - Root composer.json requires vwo/vwo-php-sdk ^1.36 -> satisfiable by vwo/vwo-php-sdk[v1.36.0, v1.36.1, v1.36.2].
    - vwo/vwo-php-sdk[v1.36.0, ..., v1.36.2] require ramsey/uuid ^3.8 -> found ramsey/uuid[3.8.0, ..., 3.x-dev] but the package is fixed to 4.2.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

`composer require vwo/vwo-php-sdk -W`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires vwo/vwo-php-sdk ^1.36 -> satisfiable by vwo/vwo-php-sdk[v1.36.0, v1.36.1, v1.36.2].
    - vwo/vwo-php-sdk[v1.36.0, ..., v1.36.2] require ramsey/uuid ^3.8 -> found ramsey/uuid[3.8.0, ..., 3.x-dev] but these were not loaded, likely because it conflicts with another require.
```

`composer require vwo/vwo-php-sdk:*`
`no matches found: vwo/vwo-php-sdk:*`

According to the `ramsey/uuid` [page on the major version update](https://uuid.ramsey.dev/en/stable/upgrading/3-to-4.html), it should require only minimal changes to update to version 4. If you'd like, I could create a pull request to update this. What I think may work well is this requirement:

> If you maintain a public project that uses ramsey/uuid version 3 and you find that your code does not require any changes to upgrade to version 4, consider using the following version constraint in your project’s composer.json file:

`composer require ramsey/uuid:"^3 || ^4"`

This should allow other projects with an older version of `ramsey/uuid` to continue using version 3. What I'm not sure about is if there are any changes that would need to be made in the `vwo-php-sdk` in order to accomodate version 4. For my part, I don't believe we will be using this UUID functionality, but I'm not sure.

Until this is resolved, I'm planning to use [a fork of this repo](https://github.com/stephenburgess8/vwo-php-sdk) to be able to install the SDK in Laravel. I will proceed with a forked version of the repo using the require statement listed above, until hopefully this project can be installed in a Laravel project with a recent Laravel version.

The way I am accomplishing this is to have created a branch in my fork called `dev-uuid-version` (the `dev-` prefix is important for the convention) with the [above change](https://github.com/stephenburgess8/vwo-php-sdk/blob/dev-uuid-version/composer.json#L12) to the requirement.

Then, in the project that I'm trying to install this package in, I've updated the composer.json to include a link to my forked repository.

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/stephenburgess8/vwo-php-sdk"
        }
    ]
```

Then for the `vwo-php-sdk`, I've changed the requirement to be

`"vwo/vwo-php-sdk": "dev-uuid-version"` as per the branch I named that way.

Doing this, I am able to successfully install the vwo-php-sdk. I will continue working on my implementation for now, and will report any bugs or issues I encounter. Let me know if you'd like me to make a pull request with the change in the requirement to allow both versions 3 and 4. Thanks.

**Comment by softvar** [comment]
We have fixed the issue in `v1.37.0`. Please try once and let us know if this fixes the issue at your end.
Here's the changelog - [https://github.com/wingify/vwo-php-sdk/blob/master/CHANGELOG.md#1370---2022-06-20](https://github.com/wingify/vwo-php-sdk/blob/master/CHANGELOG.md#1370---2022-06-20 )
