### ISSUE TITLE
Codesniffer - require

### ISSUE THREAD

**Issue by KasperFranz** [wingify/vwo-php-sdk#2]
Hi,

Thank you for providing this SDK.

When looking through the composer file for the project - I can see that php_codesniffer is required for this SDK.

I am guessing that php_codesniffer is only required for dev? 

If that is the case can it be moved to the dev requirements? 

Thank you

**Comment by softvar** [comment]
Hey @KasperFranz ,

Thanks for pointing this out. We have fixed it now. Please update SDK to the latest version.
