### ISSUE TITLE
README - demo code provided uses the wrong function!

### ISSUE THREAD

**Issue by YaronMiro** [wingify/vwo-php-sdk#8]
On the main README.md file you provide a sample code to illustrate the usage of the SDK, but your using a "private" function `getVariation()` instead of using the public function `getVariationName()` of the `VWO` SDK class.

**Wrong function** (Private)
```php
<?php
$vwoClient = new VWO($sdkConfig);
$variation = $vwoClient->getVariation($campaignKey, $userId, $options);

```
**Correct function** (Public)
```php
<?php
$vwoClient = new VWO($sdkConfig);
$variation = $vwoClient->getVariationName($campaignKey, $userId, $options);

```

Please correct this, since its misleading.

Thank You

**Comment by YaronMiro** [comment]
I see that you fixed thanks 👍

**Comment by softvar** [comment]
Thanks, @YaronMiro for letting us know.
